// <auto-generated />
using System;
using Hiredaily.Modules.Identity.Infra.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infra.Migrations
{
    [DbContext(typeof(IdentityDbContext))]
    partial class IdentityDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Hiredaily.Modules.Identity.Application.Models.RefreshTokenStore", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedAt");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("ExpiresAt");

                    b.Property<Guid?>("OrganizationId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("OrganizationId");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)")
                        .HasColumnName("Token");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("UserId");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAt");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.ToTable("RefreshTokenStores", (string)null);
                });

            modelBuilder.Entity("Hiredaily.Modules.Identity.Domain.Organization.Organization", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("PasswordHash");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)")
                        .HasColumnName("Email");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Organizations", (string)null);
                });

            modelBuilder.Entity("Hiredaily.Modules.Identity.Domain.User.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("PasswordHash");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("Hiredaily.Modules.Identity.Domain.Organization.Organization", b =>
                {
                    b.OwnsOne("Hiredaily.Modules.Identity.Domain.Organization.ValueObjects.OrganizationAddress", "Address", b1 =>
                        {
                            b1.Property<Guid>("OrganizationId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<bool>("IsInitialized")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("bit")
                                .HasDefaultValue(true)
                                .HasColumnName("AddressInitialized");

                            b1.HasKey("OrganizationId");

                            b1.ToTable("Organizations");

                            b1.WithOwner()
                                .HasForeignKey("OrganizationId");

                            b1.OwnsOne("Hiredaily.BuildingBlocks.Domain.ValueObjects.GeoLocation", "Location", b2 =>
                                {
                                    b2.Property<Guid>("OrganizationAddressOrganizationId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<string>("Lat")
                                        .HasMaxLength(32)
                                        .HasColumnType("nvarchar(32)")
                                        .HasColumnName("Latitude");

                                    b2.Property<string>("Long")
                                        .HasMaxLength(32)
                                        .HasColumnType("nvarchar(32)")
                                        .HasColumnName("Longitude");

                                    b2.HasKey("OrganizationAddressOrganizationId");

                                    b2.ToTable("Organizations");

                                    b2.WithOwner()
                                        .HasForeignKey("OrganizationAddressOrganizationId");
                                });

                            b1.OwnsOne("Hiredaily.BuildingBlocks.Domain.ValueObjects.PostalAddress", "PostalAddress", b2 =>
                                {
                                    b2.Property<Guid>("OrganizationAddressOrganizationId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<string>("AddressLine1")
                                        .HasMaxLength(300)
                                        .HasColumnType("nvarchar(300)")
                                        .HasColumnName("AddressLine1");

                                    b2.Property<string>("AddressLine2")
                                        .HasMaxLength(300)
                                        .HasColumnType("nvarchar(300)")
                                        .HasColumnName("AddressLine2");

                                    b2.Property<string>("City")
                                        .HasMaxLength(120)
                                        .HasColumnType("nvarchar(120)")
                                        .HasColumnName("City");

                                    b2.Property<string>("Country")
                                        .HasMaxLength(120)
                                        .HasColumnType("nvarchar(120)")
                                        .HasColumnName("Country");

                                    b2.Property<string>("PostalCode")
                                        .HasMaxLength(32)
                                        .HasColumnType("nvarchar(32)")
                                        .HasColumnName("PostalCode");

                                    b2.Property<string>("State")
                                        .HasMaxLength(120)
                                        .HasColumnType("nvarchar(120)")
                                        .HasColumnName("State");

                                    b2.HasKey("OrganizationAddressOrganizationId");

                                    b2.ToTable("Organizations");

                                    b2.WithOwner()
                                        .HasForeignKey("OrganizationAddressOrganizationId");
                                });

                            b1.OwnsOne("Hiredaily.Modules.Identity.Domain.Organization.ValueObjects.OrganizationContactDetails", "ContactDetails", b2 =>
                                {
                                    b2.Property<Guid>("OrganizationAddressOrganizationId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<string>("Email")
                                        .HasMaxLength(320)
                                        .HasColumnType("nvarchar(320)")
                                        .HasColumnName("ContactEmail");

                                    b2.Property<string>("Phone")
                                        .HasMaxLength(32)
                                        .HasColumnType("nvarchar(32)")
                                        .HasColumnName("Phone");

                                    b2.Property<string>("WebsiteUrl")
                                        .HasMaxLength(500)
                                        .HasColumnType("nvarchar(500)")
                                        .HasColumnName("WebsiteUrl");

                                    b2.HasKey("OrganizationAddressOrganizationId");

                                    b2.ToTable("Organizations");

                                    b2.WithOwner()
                                        .HasForeignKey("OrganizationAddressOrganizationId");
                                });

                            b1.Navigation("ContactDetails")
                                .IsRequired();

                            b1.Navigation("Location")
                                .IsRequired();

                            b1.Navigation("PostalAddress")
                                .IsRequired();
                        });

                    b.Navigation("Address")
                        .IsRequired();
                });

            modelBuilder.Entity("Hiredaily.Modules.Identity.Domain.User.User", b =>
                {
                    b.OwnsMany("Hiredaily.BuildingBlock.Domain.ValueObjects.Skill", "Skills", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("Id"));

                            b1.Property<string>("Description")
                                .HasMaxLength(1000)
                                .HasColumnType("nvarchar(1000)");

                            b1.Property<string>("Field")
                                .HasMaxLength(120)
                                .HasColumnType("nvarchar(120)");

                            b1.Property<string>("Name")
                                .HasMaxLength(120)
                                .HasColumnType("nvarchar(120)");

                            b1.Property<string>("SkillLevel")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)");

                            b1.Property<Guid>("UserId")
                                .HasColumnType("uniqueidentifier");

                            b1.HasKey("Id");

                            b1.HasIndex("UserId");

                            b1.ToTable("UserSkills", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.OwnsOne("Hiredaily.Modules.Identity.Domain.User.ValueObject.UserAddress", "Address", b1 =>
                        {
                            b1.Property<Guid>("UserId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<bool>("IsInitialized")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("bit")
                                .HasDefaultValue(true)
                                .HasColumnName("AddressInitialized");

                            b1.HasKey("UserId");

                            b1.ToTable("Users");

                            b1.WithOwner()
                                .HasForeignKey("UserId");

                            b1.OwnsOne("Hiredaily.BuildingBlocks.Domain.ValueObjects.GeoLocation", "Locatoin", b2 =>
                                {
                                    b2.Property<Guid>("UserAddressUserId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<string>("Lat")
                                        .HasMaxLength(32)
                                        .HasColumnType("nvarchar(32)")
                                        .HasColumnName("Latitude");

                                    b2.Property<string>("Long")
                                        .HasMaxLength(32)
                                        .HasColumnType("nvarchar(32)")
                                        .HasColumnName("Longitude");

                                    b2.HasKey("UserAddressUserId");

                                    b2.ToTable("Users");

                                    b2.WithOwner()
                                        .HasForeignKey("UserAddressUserId");
                                });

                            b1.OwnsOne("Hiredaily.BuildingBlocks.Domain.ValueObjects.PostalAddress", "PostalAddress", b2 =>
                                {
                                    b2.Property<Guid>("UserAddressUserId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<string>("AddressLine1")
                                        .HasMaxLength(300)
                                        .HasColumnType("nvarchar(300)")
                                        .HasColumnName("AddressLine1");

                                    b2.Property<string>("AddressLine2")
                                        .HasMaxLength(300)
                                        .HasColumnType("nvarchar(300)")
                                        .HasColumnName("AddressLine2");

                                    b2.Property<string>("City")
                                        .HasMaxLength(120)
                                        .HasColumnType("nvarchar(120)")
                                        .HasColumnName("City");

                                    b2.Property<string>("Country")
                                        .HasMaxLength(120)
                                        .HasColumnType("nvarchar(120)")
                                        .HasColumnName("Country");

                                    b2.Property<string>("PostalCode")
                                        .HasMaxLength(32)
                                        .HasColumnType("nvarchar(32)")
                                        .HasColumnName("PostalCode");

                                    b2.Property<string>("State")
                                        .HasMaxLength(120)
                                        .HasColumnType("nvarchar(120)")
                                        .HasColumnName("State");

                                    b2.HasKey("UserAddressUserId");

                                    b2.ToTable("Users");

                                    b2.WithOwner()
                                        .HasForeignKey("UserAddressUserId");
                                });

                            b1.OwnsOne("Hiredaily.Modules.Identity.Domain.User.ValueObject.UserContactDetails", "ContactDetails", b2 =>
                                {
                                    b2.Property<Guid>("UserAddressUserId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<string>("Email")
                                        .HasMaxLength(320)
                                        .HasColumnType("nvarchar(320)")
                                        .HasColumnName("Email");

                                    b2.Property<string>("Phone")
                                        .HasMaxLength(32)
                                        .HasColumnType("nvarchar(32)")
                                        .HasColumnName("Phone");

                                    b2.HasKey("UserAddressUserId");

                                    b2.ToTable("Users");

                                    b2.WithOwner()
                                        .HasForeignKey("UserAddressUserId");
                                });

                            b1.Navigation("ContactDetails")
                                .IsRequired();

                            b1.Navigation("Locatoin")
                                .IsRequired();

                            b1.Navigation("PostalAddress")
                                .IsRequired();
                        });

                    b.Navigation("Address")
                        .IsRequired();

                    b.Navigation("Skills");
                });
#pragma warning restore 612, 618
        }
    }
}
