<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>Hiredaily.Modules.Identity.API</AssemblyName>
    <RootNamespace>Hiredaily.Modules.Identity.API</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="10.0.9" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../Application/Application.csproj" />
    <ProjectReference Include="../Domain/Domain.csproj" />
    <ProjectReference Include="../Infra/Infra.csproj" />
    <ProjectReference Include="..\..\..\BuildingBlock\src\API\API.csproj" />
    <ProjectReference Include="..\..\..\BuildingBlock\src\Application\Application.csproj" />
    <ProjectReference Include="..\..\..\BuildingBlock\src\Domain\Domain.csproj" />
  </ItemGroup>

</Project>
