// <auto-generated />
using System;
using Hiredaily.Modules.Jobs.Infra.Persistence.SQL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Hiredaily.Modules.Jobs.Infra.Migrations
{
    [DbContext(typeof(JobsDbContext))]
    partial class JobsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Hiredaily.Modules.Jobs.Application.Outbox.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Error")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("PublishedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("RetryCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PublishedAt");

                    b.ToTable("OutboxMessages", (string)null);
                });

            modelBuilder.Entity("Hiredaily.Modules.Jobs.Domain.Job", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Jobs", (string)null);
                });

            modelBuilder.Entity("Hiredaily.Modules.Jobs.Domain.Job", b =>
                {
                    b.OwnsOne("Hiredaily.BuildingBlock.Domain.ValueObjects.Money", "HourlyRate", b1 =>
                        {
                            b1.Property<Guid>("JobId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("HourlyRateAmount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("nvarchar(3)")
                                .HasColumnName("HourlyRateCurrency");

                            b1.HasKey("JobId");

                            b1.ToTable("Jobs");

                            b1.WithOwner()
                                .HasForeignKey("JobId");
                        });

                    b.OwnsMany("Hiredaily.BuildingBlock.Domain.ValueObjects.Skill", "RequiredSkills", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("Id"));

                            b1.Property<string>("Description")
                                .IsRequired()
                                .HasMaxLength(1000)
                                .HasColumnType("nvarchar(1000)");

                            b1.Property<string>("Field")
                                .IsRequired()
                                .HasMaxLength(120)
                                .HasColumnType("nvarchar(120)");

                            b1.Property<Guid>("JobId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(120)
                                .HasColumnType("nvarchar(120)");

                            b1.Property<string>("SkillLevel")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)");

                            b1.HasKey("Id");

                            b1.HasIndex("JobId");

                            b1.ToTable("JobRequiredSkills", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("JobId");
                        });

                    b.OwnsOne("Hiredaily.Modules.Jobs.Domain.ValueObjects.JobSite", "JobSite", b1 =>
                        {
                            b1.Property<Guid>("JobId")
                                .HasColumnType("uniqueidentifier");

                            b1.HasKey("JobId");

                            b1.ToTable("Jobs");

                            b1.WithOwner()
                                .HasForeignKey("JobId");

                            b1.OwnsOne("Hiredaily.BuildingBlock.Domain.ValueObjects.GeoLocation", "Location", b2 =>
                                {
                                    b2.Property<Guid>("JobSiteJobId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<string>("Lat")
                                        .IsRequired()
                                        .HasMaxLength(32)
                                        .HasColumnType("nvarchar(32)")
                                        .HasColumnName("Latitude");

                                    b2.Property<string>("Long")
                                        .IsRequired()
                                        .HasMaxLength(32)
                                        .HasColumnType("nvarchar(32)")
                                        .HasColumnName("Longitude");

                                    b2.HasKey("JobSiteJobId");

                                    b2.ToTable("Jobs");

                                    b2.WithOwner()
                                        .HasForeignKey("JobSiteJobId");
                                });

                            b1.OwnsOne("Hiredaily.BuildingBlock.Domain.ValueObjects.PostalAddress", "Address", b2 =>
                                {
                                    b2.Property<Guid>("JobSiteJobId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<string>("AddressLine1")
                                        .IsRequired()
                                        .HasMaxLength(300)
                                        .HasColumnType("nvarchar(300)")
                                        .HasColumnName("AddressLine1");

                                    b2.Property<string>("AddressLine2")
                                        .HasMaxLength(300)
                                        .HasColumnType("nvarchar(300)")
                                        .HasColumnName("AddressLine2");

                                    b2.Property<string>("City")
                                        .IsRequired()
                                        .HasMaxLength(120)
                                        .HasColumnType("nvarchar(120)")
                                        .HasColumnName("City");

                                    b2.Property<string>("Country")
                                        .IsRequired()
                                        .HasMaxLength(120)
                                        .HasColumnType("nvarchar(120)")
                                        .HasColumnName("Country");

                                    b2.Property<string>("PostalCode")
                                        .IsRequired()
                                        .HasMaxLength(32)
                                        .HasColumnType("nvarchar(32)")
                                        .HasColumnName("PostalCode");

                                    b2.Property<string>("State")
                                        .IsRequired()
                                        .HasMaxLength(120)
                                        .HasColumnType("nvarchar(120)")
                                        .HasColumnName("State");

                                    b2.HasKey("JobSiteJobId");

                                    b2.ToTable("Jobs");

                                    b2.WithOwner()
                                        .HasForeignKey("JobSiteJobId");
                                });

                            b1.Navigation("Address")
                                .IsRequired();

                            b1.Navigation("Location")
                                .IsRequired();
                        });

                    b.Navigation("HourlyRate")
                        .IsRequired();

                    b.Navigation("JobSite")
                        .IsRequired();

                    b.Navigation("RequiredSkills");
                });
#pragma warning restore 612, 618
        }
    }
}
